global:
  scrape_interval: 3s
  scrape_timeout: 3s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: iotagents
  scrape_interval: 4s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - iotagent-mqtt:3000


